<a href="https://colab.research.google.com/github/WebAishwarya/Data-Analyst_Unified-Mentor/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

A = np.array([1,2,3])

In [ ]:
# print output

print(A)

[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d

print("Dimension of a : ", np.ndim(a))
print("Dimension of b : ", np.ndim(b))
print("Dimension of c : ", np.ndim(c))
print("Dimension of d : ", np.ndim(d))

Dimension of a :  0
Dimension of b :  1
Dimension of c :  2
Dimension of d :  3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d

print("Shape of a : ", np.shape(a))
print("Shape of b : ", np.shape(b))
print("Shape of c : ", np.shape(c))
print("Shape of d : ", np.shape(d))

Shape of a :  ()
Shape of b :  (3,)
Shape of c :  (2, 3)
Shape of d :  (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d

print("Datatype of a : ", a.dtype)
print("Datatype of b : ", b.dtype)
print("Datatype of c : ", c.dtype)
print("Datatype of d : ", d.dtype)

Datatype of a :  int64
Datatype of b :  int64
Datatype of c :  int64
Datatype of d :  int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable

print("Type of a : ", type(a))
print("Type of b : ", type(b))

Type of a :  <class 'numpy.ndarray'>
Type of b :  <class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function

len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.

l1 = [10,20,30]
l2 = [40,50,60]
l3 = l1
l4 = l2

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above

# List Comprehention
result = [a * b for a, b in zip(l1, l2)]
print(result)

# Total time taken to run result
%timeit result

[400, 1000, 1800]
31.1 ns ± 0.633 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:
result_2 = [a * b for a, b in zip(l3, l4)]
print(result_2)

# Total time taken to run result_2
%timeit result_2

[400, 1000, 1800]
31 ns ± 0.65 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it

B = np.arange(1,11)
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

C = np.arange(1,11,2)
C

array([1, 3, 5, 7, 9])

In [ ]:
# create numpy array using eye function with 3 as passed parameter

D = np.eye(3)
D

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16

x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# Reshape x with 3 rows and 5 columns

newarr = x.reshape(3, 5)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x = np.arange(1,17)

newarr = x.reshape(2, 4, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

arr = x.reshape(4, -1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays

y = x.reshape(2,4,-1)

# print y

print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# Flattening y

flat_y = y.reshape(-1)
print(flat_y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Create an array a with all even numbers between 1 to 17

a = np.array([i for i in range(1,17) if i%2==0])

print(a)

[ 2  4  6  8 10 12 14 16]


In [ ]:
# Get third element in array a

a[2]

6

In [ ]:
#Print 3rd, 5th, and 7th element in array a

print(a[2], a[4], a[6])

6 10 14


Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# print the 3rd element from the 3rd row of a

print(a[2][2])

9


Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.

b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

third_element = b[0][1][2]
print(third_element)

6


In [ ]:
# Create 1D array

arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Slice elements from 1st to 5th element from the following array:

slice_arr = arr[0:5]
print(slice_arr)

[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array:

a1 = arr[5:]
print(a1)

[6 7]


In [ ]:
# Slice elements from the beginning to index 5 (not included):

b = arr[:5]
print(b)

[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:

c = arr[1:7:2]
print(c)

[2 4 6]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:

d = arr[::1]
print(d)

[1 2 3 4 5 6 7]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [ ]:
# Print array a

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

a[2,1:5]

array([8, 9])

In [ ]:
# In array 'a' print index 2 from all the elements :

a[2]


array([7, 8, 9])

In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [ ]:
x1 = np.array([1,2,3,4,5])

In [ ]:
# assign x2 = x1

x2 = x1

In [ ]:
#print x1 and x2

print("x1 : ", x1)
print("x2 : ", x2)

x1 :  [1 2 3 4 5]
x2 :  [1 2 3 4 5]


Ok now you have seen that both of them are same

In [ ]:
# change 1st element of x2 as 10

x2[0] = 10

In [ ]:
#Again print x1 and x2

print("x1 : ", x1)
print("x2 : ", x2)

x1 :  [10  2  3  4  5]
x2 :  [10  2  3  4  5]


In [ ]:
# Check memory share between x1 and x2

if id(x1) == id(x2):
  print("x1 and x2 share the same memory location.")
else:
  print("x1 and x2 do not share the same memory location.")

x1 and x2 share the same memory location.


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:
# Create a view of x1 and store it in x3.

x3 = x1.view()

In [ ]:
# Again check memory share between x1 and x3

if id(x1) == id(x3):
  print("x1 and x2 share the same memory location.")
else:
  print("x1 and x2 do not share the same memory location.")

x1 and x2 do not share the same memory location.


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:
#Change 1st element of x3=100

x3[0] = 100

In [ ]:
#print x1 and x3 to check if changes reflected in both

print("x1 : ", x1)
print("x3 : ", x3)


x1 :  [100   2   3   4   5]
x3 :  [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [ ]:
# Now create an array x4 which is copy of x1

x4 = x1.copy()

In [ ]:
# Change the last element of x4 as 900

x4[-1] = 900

In [ ]:
# print both x1 and x4 to check if changes reflected in both

print("x1 : ", x1)
print("x4 : ", x4)

x1 :  [100   2   3   4   5]
x4 :  [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:
#Check memory share between x1 and x4

if id(x1) == id(x4):
  print("x1 and x2 share the same memory location.")
else:
  print("x1 and x2 do not share the same memory location.")


x1 and x2 do not share the same memory location.


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [ ]:
# stack x1 and x4 along columns.

result_1 = np.vstack((x1,x4))
print(result_1)

[[100   2   3   4   5]
 [100   2   3   4 900]]


In [ ]:
#stack x1 and x4 along rows

result_2 = np.hstack((x1,x4))
print(result_2)

[100   2   3   4   5 100   2   3   4 900]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [ ]:
arr1 = np.array([[1,2],[4,5]])

arr2 = np.array([[3,4],[6,7]])

##join arr1 and arr2 along rows using concatenate() function

arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2]
 [4 5]
 [3 4]
 [6 7]]


In [ ]:
##join arr1 and arr2 along columns using concatenate() function

arr4 = np.concatenate((arr1,arr2),axis=1)
print(arr4)

[[1 2 3 4]
 [4 5 6 7]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:
# append arr2 to arr1

print(np.append(arr2,arr1))

[3 4 6 7 1 2 4 5]


Lets use insert() function which Inserts values into array before specified index value

In [ ]:
# Inserts values into array x1 before index 4 with elements of x4

print(np.insert(x1,4,x4))

[100   2   3   4 100   2   3   4 900   5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
# delete 2nd element from array x2

print(np.delete(x2,2))

[100   2   4   5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!