<a href="https://colab.research.google.com/github/WebAishwarya/Data-Analyst_Unified-Mentor/blob/main/Python_Numpy_Basics_Day6_UnifiedMentor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DAY 6

---



# 6.1 Numpy Array Dimensions

1D Array

2D Array

3D Array

In [ ]:
import numpy as np     # importing numpy library

In [ ]:
A = np.array(5)        # Scalar Array
A

array(5)

In [ ]:
np.ndim(A)               # Dimension method

0

In [ ]:
One = np.array([1, 2, 3, 4, 5])           # Single square bracket
Two = np.array([[1, 2, 3], [4, 5, 6]])    # Double square brackets
Three = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [ ]:
One

array([1, 2, 3, 4, 5])

In [ ]:
np.ndim(One)

1

In [ ]:
Two

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ndim(Two)

2

In [ ]:
Three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#Three.shape
np.ndim(Three)

3

# List vs Numpy Array

In [ ]:
list1 = [1, 4.0, 'apple']                   # List - Different Datatypes
arr = np.array([1, 2, 3, 4, 5])             # Array - Similar Datatypes

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([1, 2, 3.9, 'apple'])        # Type Conversion

In [ ]:
arr       # Now all the elements is of string datatype

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr = np.array([1, 2, 3, 4, 5])             # Allows Mathematical Operations

arr/5
#list1/5   - lists not allows divide the element at the same time  - Generates TypeError

array([0.2, 0.4, 0.6, 0.8, 1. ])

# More Advantages of Numpy Array over list

*   Array consumes less memory
*   Array are faster than lists



# 6.2 Array Reshaping & Indexing

# Reshaping arrays

Reshaping means changing the shape of an array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])   # 1D Array

# 1D to 2D Array
newarr = arr.reshape(4, 3)  # 4-Rows 3-Columns

In [ ]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 1D to 3D Array

newarr = arr.reshape(2, 3, 2)    # x,y,z: x = matrix, y = rows, z = cols

In [ ]:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [ ]:
arr = np.array([1, 2, 3, 4])              # Accessing 1D Array

print(arr[3])

4


In [ ]:
print(arr[2] + arr[3])                 # Addition of 2 elements

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  # Accessing 2D Array
arr.shape

print(arr[0, 1])                          # 1st row 2nd element
print(arr[1, 4])                          # 2nd row 5th element

2
10


In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   # Accessing 3D Array

print(arr3[0, 1, 2])               # 0th matrix, 1st row, 3rd column
print(arr3[1, 1, 0])               # 1st matrix, 2nd row, 1st column
print(arr3[0, 1, 0])

6
10
4


In [ ]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3.shape

(2, 2, 3)